version: "3.9"

services:
  # web:
  #   build: .
  #   container_name: jestor-api
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - dbaecm
  #   environment:
  #     - DB_HOST=${DATABASE_HOST}
  #     - DB_NAME=${DATABASE_NAME}
  #     - DB_USER=${DATABASE_USER}
  #     - DB_PASSWORD=${DATABASE_PASSWORD}

  dbaecm:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
