### ====== GET ALL PRODUCTS ======
GET http://127.0.0.1:8000/jestor/products/?na_product=&sku=013

### ====== GET ALL CATEGORIES
GET http://127.0.0.1:8000/jestor/categories/?na_category=C

### ====== INSERT PRODUCT ======
POST http://127.0.0.1:8000/jestor/products/
Content-Type: application/json

{
    "nce": 13,
    "cd_color": 1,
    "cd_marca": 1,
    "na_product": "VENTILADOR ELETROLUX",
    "na_description": "",
    "total_vl": 323.97,
    "installments": null,
    "images": null
}

### ====== INSERT CATEGORY ======
POST http://127.0.0.1:8000/jestor/categories/
Content-Type: application/json

{
    "cd_category": 3,
    "na_category": "Quarto"
}